name: Verify build 

on:
  pull_request:
    branches:
      - 'main'

jobs:
  x86_64-unknown-linux-musl:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-musl --bins --release
      - name: Rename binaries
        run: mv target/x86_64-unknown-linux-musl/release/bot bot_amd64 && mv target/x86_64-unknown-linux-musl/release/cron cron_amd64
      - name: Upload AMD64 binaries
        uses: actions/upload-artifact@v3
        with:
          name: amd64
          path: "*_amd64"

  aarch64-unknown-linux-musl:
    name: Linux ARM64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-musl --bins --release
      - name: Rename binaries
        run: mv target/aarch64-unknown-linux-musl/release/bot bot_arm64 && mv target/aarch64-unknown-linux-musl/release/cron cron_arm64
      - name: Upload ARM64 binaries
        uses: actions/upload-artifact@v3
        with:
          name: arm64
          path: "*_arm64"

